### PR TITLE
Update .sh folders to match structure

### PR DESCRIPTION
**Pull request by colts45s**
Updating the the folders in the Copy directories section to reflect the file structure within the repository

### CODE REVIEW

**Comment by simeononsecurity** [comment]
Good catch @colts45s this was a copy error on our part.
Unfortunately we have internal requirements for contribution credit and a change this small isn't per say what we're looking for. 
However, we did make the change here.
https://github.com/simeononsecurity/FireFox-Privacy-Script/commit/1c445d531204c271668fafebe46a2bad8543a130

**Comment by colts45s** [comment]
No worries. I don't particularly need any credit, but I also did not see a contribution note on a process. Thanks for taking a look at this though 👍

**Comment by dubsalot** [comment]
> Unfortunately we have internal requirements for contribution credit and a change this small isn't **per say** what we're looking for

\* **per se**

**Comment by simeononsecurity** [comment]
> > Unfortunately we have internal requirements for contribution credit and a change this small isn't **per say** what we're looking for
> 
> * **per se**

VTT still isn't perfect.

**Pull request closed without merging**
